version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pulsefolio_postgres
    restart: always
    environment:
      POSTGRES_DB: pulsefolio_db
      POSTGRES_USER: portfoliouser
      POSTGRES_PASSWORD: SaiVittalPortfolio@20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: pulsefolio_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: pulsefolio_rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: saiadmin123
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: ./backend
      dockerfile: Pulsefolio.API/Dockerfile
    container_name: pulsefolio_api
    restart: always
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://0.0.0.0:8080" 
      
      # Postgres env
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=pulsefolio_db;Username=portfoliouser;Password=SaiVittalPortfolio@20"

      # RabbitMQ env
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: "admin"
      RabbitMQ__Password: "saiadmin123"

      # Redis env
      Redis__Host: "redis"
      Redis__Port: "6379"

  worker:
    build:
      context: ./backend
      dockerfile: Pulsefolio.Workers/Dockerfile
    container_name: pulsefolio_worker
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  nginx:
    image: nginx:latest
    container_name: pulsefolio_nginx
    restart: always
    ports:
      # Expose standard HTTP and HTTPS ports to the world
      - "80:80"
      - "443:443"
    volumes:
      # Mount the custom configuration
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Volume for Certbot verification webroot
      - certbot_web:/var/www/certbot
      # Volume for Certbot certificates (where Nginx reads them)
      - certbot_certs:/etc/letsencrypt
    depends_on:
      - api # Ensure Nginx starts after the API
      
  # --- CERTBOT SERVICE for SSL/TLS ---
  certbot:
    image: certbot/certbot
    container_name: pulsefolio_certbot
    volumes:
      - certbot_web:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    command: certbot renew --dry-run
    
volumes:
  postgres_data:
  certbot_web:
  certbot_certs: